security:
    encoders:
        App\Entity\User: 'auto'

    providers:
        database_users:
            entity: { class: App\Entity\User, property: username }

    
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            pattern: ^/
            anonymous: true
            lazy: true
            provider: database_users
            form_login:
                check_path: security_login
                login_path: security_login
                csrf_token_generator: security.csrf.token_manager
                default_target_path: blog_index
            logout:
                path: security_logout
                target: homepage

    
    access_control:
        - { path: '^/(%app_locales%)/admin', roles: ROLE_ADMIN }

    role_hierarchy:
        ROLE_ADMIN: ROLE_USER
