# These lines define a route using YAML configuration. The controller used by
# the route (FrameworkBundle:Template:template) is a convenient shortcut when
# the template can be rendered without executing any logic in your own controller.
# See https://symfony.com/doc/current/templates.html#rendering-a-template-directly-from-a-route
homepage:
    path: /{_locale}
    controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController::templateAction
    requirements:
        _locale: '%app_locales%'
    defaults:
        template: default/homepage.html.twig
        _locale: '%locale%'

admin_loggedin_index:
    path: /{_locale}/admin/loggedin/home
    controller: App\Controller\Admin\IndexController::index
    methods:  [GET]
    defaults:
        _locale: '%locale%'

admin_user_index:
    path: /{_locale}/admin/user
    controller: App\Controller\Admin\UserController::users
    methods: [GET]
    defaults:
        _locale: '%locale%'

admin_user_new:
    path: /{_locale}/admin/user/new
    controller: App\Controller\Admin\UserController::new
    methods: [GET|POST]
    defaults:
        _locale: '%locale%'

admin_user_show:
    path: /{_locale}/admin/user/{id}
    controller: App\Controller\Admin\UserController::show
    methods: [GET]
    defaults:
        _locale: '%locale%'

admin_user_edit:
    path: /{_locale}/admin/user/{id}/edit
    controller: App\Controller\Admin\UserController::edit
    methods: [GET|POST]
    defaults:
        _locale: '%locale%'

admin_user_delete:
    path: /{_locale}/admin/user/{id}/delete
    controller: App\Controller\Admin\UserController:delete
    methods: [POST]
    defaults:
        _locale: '%locale%'

admin_tags_index:
    path: /{_locale}/admin/tags
    controller: App\Controller\Admin\TagController:tags
    methods: [GET]
    defaults:
        _locale: '%locale%'