parameters:
    locale: 'pl'
    app_locales: en|de|pl
    app.notifications.email_sender: anonymous@example.com

services:
    _defaults:
        autowire: true
        autoconfigure: true
        bind:
            string $locales: '%app_locales%'
            string $defaultLocale: '%locale%'
            string $emailSender: '%app.notifications.email_sender%'


    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
            - '../src/Tests/'


    App\Controller\:
        resource: '../src/Controller/'
        tags: ['controller.service_arguments']


    App\EventSubscriber\CommentNotificationSubscriber:
        $sender: '%app.notifications.email_sender%'
